### ISSUE TITLE
Fatal error: Cannot override final method

### ISSUE THREAD

**Issue by jwalits** [Wunderbyte-GmbH/moodle-local_wunderbyte_table#48]
We are currently seeing the following error with the mod/booking plugin and the issue arises from `local_wunderbyte_table\wunderbyte_table` class defining the __construct method as final

![2024-02-21_12-46](https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/assets/56375964/3087135b-53c3-4ff4-81f1-269b11d23ffc)

**Comment by georgmaisser** [comment]
Hi, thank you for your contribution!

The last version of booking is compatible with the new "final" constructor. The reason we added it was that because of the caching of the wb table class, there is a risk of passing on the wrong class instance to the wrong user. Passing on values in the constructor and storing them in the class increases the risk of unwanted effects.

But I see that we need to stay backwards compatible for a while.
